### ISSUE TITLE
PushTracker Mobile UI Development

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#10]
![PT-MOBILE-MAIN-V2](https://user-images.githubusercontent.com/213467/59945903-99211780-942e-11e9-9710-1e3d1da39858.png)
![PT-MOBILE-JOURNEY](https://user-images.githubusercontent.com/213467/59945902-99211780-942e-11e9-9b5f-c1d6bb12980f.png)
![PT-MOBILE-MYACTIVITY](https://user-images.githubusercontent.com/213467/59945904-99211780-942e-11e9-8612-efbda321b0ab.png)
![PT-MOBILE-PROFILE](https://user-images.githubusercontent.com/213467/59945905-99211780-942e-11e9-96a9-21cf9f76f33a.png)
![PT-MOBILE-SETTINGS](https://user-images.githubusercontent.com/213467/59945906-99211780-942e-11e9-9adc-4c8c12a92607.png)

**Comment by bradmartin** [comment]
Isolated the screens into individual issues to break apart dev work
