### ISSUE TITLE
Design Login Screen

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#102]

**Comment by finger563** [comment]
The space at the top should be used for the App icon / Permobil Logo
![PT-MOBILE-LOGIN_ALT](https://user-images.githubusercontent.com/213467/62807165-4d97fb00-baba-11e9-9284-823ec2b06fae.png)

**Comment by finger563** [comment]
Thanks @ken-max !

**Comment by finger563** [comment]
Assigning @bradmartin  since he self-assigned #110

**Comment by bradmartin** [comment]
I'll get this today 👍

**Comment by bradmartin** [comment]
Closed via https://github.com/Max-Mobility/permobil-client/pull/148
