### ISSUE TITLE
Design Splash Screen for PT.M

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#120]

**Comment by bradmartin** [comment]
@ken-max do you also know what the app icon will be?

**Comment by bradmartin** [comment]
Waiting on permobil marketing for this.

**Comment by finger563** [comment]
* https://docs.nativescript.org/tooling/publishing/creating-launch-screens-ios
* https://docs.nativescript.org/tooling/publishing/creating-launch-screens-android

**Comment by finger563** [comment]
So from marketing we need the logo and background color; the design will (for now) be the app logo with the permobil logo underneath and some background

**Comment by finger563** [comment]
Background either black or  Permobil Royal Blue – RGB: 40 98 142.

![PushTracker_SplashScreen](https://user-images.githubusercontent.com/213467/64557912-368e3800-d308-11e9-9e9f-21b9abbdc10a.png)

**Comment by bradmartin** [comment]
Android - https://github.com/Max-Mobility/permobil-client/blob/master/apps/mobile/pushtracker/App_Resources/Android/src/main/res/drawable-nodpi/splash_screen.xml (need a png for the background) already have the logo in drawables so should be easy enough to change the ref in the layer-list

**Comment by p-ranav** [comment]
@bradmartin Can you do this for iOS? I don't have an Apple device to test with.

**Comment by bradmartin** [comment]
yea I'll do that, I totally forgot about this tool http://images.nativescript.rocks/# - lets you select the background color instead of needing to do photoshopping image work 👍 So I'll do that now.
