### ISSUE TITLE
update home page to use the user's goals directly

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#123]
Currently it uses simple databinding to public members of the home-tab class which are loaded (on init) from the appSettings. This means that they are not properly updated for instance if the user changes, or if the data for the user changes from the server (or from the profile-tab).  Moving to directly binding to the user's preferences will fix these issues.

**Comment by finger563** [comment]
@p-ranav  has this been closed by https://github.com/Max-Mobility/permobil-client/commit/d761e7fd688c2dcf1e6225e232ecae8012d769bc ?

**Comment by p-ranav** [comment]
The relevant data is available in the database but we need to update the home tab to pull it up and display correctly. This requires two tasks:

1. Make sure that the home tab on first load shows the correct activity goals
2. Go to the Profile tab and change the activity goals. Then, return to the home tab. The activity goals in the home tab should correctly show the changed values.

1 is trivial and I can update the home tab. For 2, we need to make sure that onNavigationEnd, the home tab updates its state and shows the correct values - I haven't gotten this working yet.
