### ISSUE TITLE
SD.W first load style issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#133]
on first load (from install from the store) the screen has a white background and the elements are not styled properly - indicating the style has not loaded properly.  It stays this way even through interaction until the screen state goes into ambient.

**Comment by finger563** [comment]
Could be related to this:
```
2019-09-04 10:54:53.619 8571-8571/com.permobil.smartdrive.wearos D/TNS.Runtime: V8 version 7.5.288.22
2019-09-04 10:54:57.426 8571-8571/com.permobil.smartdrive.wearos E/JS: Error: Could not load CSS from app.css: Error: require's first parameter should be string
2019-09-04 10:54:57.538 8571-8571/com.permobil.smartdrive.wearos I/JS: load language files: 90.00ms
2019-09-04 10:54:57.538 8571-8571/com.permobil.smartdrive.wearos I/JS: App_Start_Time: 90.00ms
```

**Comment by finger563** [comment]
looks like it might be related to [this discussion](https://discourse.nativescript.org/t/nativescript-webpack-version-dont-load-platform-css/2294/9)

**Comment by finger563** [comment]
@bradmartin do you know what might be causing it? Thought it might be related to webpack or some dependency but I'm not sure

**Comment by finger563** [comment]
error that was shown was due to missing `app.css` file.  have added empty one for now.

We think that the style issue could be partially related to build issues that cause css files to not be generated from scss files. for now we'll manually run `npm run scss` from within the `apps/<platform>/<app>` folder to generate the css prior to rolling out a build.

**Comment by finger563** [comment]
for reference - a build that includes css and has app.css does not prevent style issues (e.g. if you have the app loaded and running, then go into the watch settings -> app info -> smartdrive mx2+ -> clear data, the next time you load the app it will load as displayed in the image above

**Comment by finger563** [comment]
Which is potentially related to how the app starts up and applies styles - @bradmartin  do you have any idea how to ensure that either default or ambient styles are applied as the app's style? Ideally it would just be pointing the app.css to one of the generated themes?

**Comment by bradmartin** [comment]
so you `cleared data`? did you add the files during a livesync/dev session? If so, I'd do a test of a build /run then disconnecting the livesync and unplug the watch and clear data and see if you see same behavior.

I believe clearing the data likely deleted the temp files that aren't packaged in the APK during livesync/dev flow.

To default to the `default` styles, we can drop the `default` styles into the `app.css` - might require a little tweaking with all the scss but it's possible for now to ensure the styles apply correctly until we can dig more into it.

**Comment by finger563** [comment]
yea i did copy the generated default css file into `app.css` for now. between that and building after running `npm run scss` to generate all the css files, i'm not seeing the behavior on the apk that was pushed to the store - even when i delete the data and such.

**Comment by finger563** [comment]
I believe this has been fixed - the only style issues remaining (so far) are #267 and #259
