### ISSUE TITLE
Add SmartDrive serial number field to profile tab or settings page

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#134]
which allows either manual text entry or the use of the qr code reader like we used in the eval app.

also need to decide where we store the smartdrive serial number.  potentially as another field of the user? we may also have a pushtracker serial number (which could be added from the app - for original pushtrackers - or from the actual SD.W app)

**Comment by p-ranav** [comment]
At the moment, everything except SmartDrive settings go inside the User collection. Might as well add this to the list.
