### ISSUE TITLE
Coast Time and Distance are undefined after sign up

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#151]
In the Profile tab, coast time and distance are undefined

**Comment by bradmartin** [comment]
Ping me @finger563 later on what the defaults should be and I'll add it.

**Comment by bradmartin** [comment]
I put the defaults here for sign up https://github.com/Max-Mobility/permobil-client/blob/master/apps/mobile/pushtracker/src/app/modules/sign-up/sign-up.component.ts#L41  - LMK what we should use for the default goals @finger563
