### ISSUE TITLE
Default values in Profile tab after sign up

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#152]
How to reproduce:
1. Sign up as a new user
2. Go to the Profile page

The following do not have default values:

- [x] Gender
- [x] Chair Type
- [x] Chair Make
- [x] Device Serial Numbers for SmartDrive and PushTracker

For list pickers, we probably need to show `Choose from List` if the entry has no value instead of leaving these blank. For serial numbers, we can have something like `Tap to Scan` as the displayed value.

**Comment by bradmartin** [comment]
@finger563 - what do you want as the default on account creation? Anything specific or just empty/0 values?

**Comment by p-ranav** [comment]
@finger563 Can you comment?

**Comment by finger563** [comment]
Default values should be empty - that way we don't inadvertently get incorrect data about users (for analysis later) simply because they didn't want to change / enter anything.

**Comment by p-ranav** [comment]
Empty as in empty string? Maybe we should show "Choose from List" in the list pickers if the value is empty string?

**Comment by finger563** [comment]
Yes, agreed - the hint should be sufficient
