### ISSUE TITLE
Default values for Height, Weight and Distance unit preference on sign up

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#153]
How to reproduce:
1. Sign up as a new user
2. Go to the Profile settings tab

Units for Height, Weight and Distance will be empty. 

If these are empty, then the user cannot properly set weight, height and distance in the Profile tab.

**Comment by bradmartin** [comment]
Should we just set these to `0` for now?

**Comment by p-ranav** [comment]
Yeah I suppose. We should be doing this as part of `Sign Up` right? - Initializing the different fields in the User object of the signed up user?

**Comment by bradmartin** [comment]
Yea I'll just put them on the object for `signup` and they'll be in the DB as defaults at least.

**Comment by bradmartin** [comment]
Defaults in place: https://github.com/Max-Mobility/permobil-client/blob/master/apps/mobile/pushtracker/src/app/modules/sign-up/sign-up.component.ts#L41 feel free to change if they seem odd as the default.
