### ISSUE TITLE
Email should be treated in a case insensitive manner when processing login attempts

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#172]
If the first letter of the email is capitalized, e.g., "Pranav.kumar@permobil.com", which is common in mobile, login does not work.

**Comment by bradmartin** [comment]
This one is strange. Maybe it's a setting on Kinvey side of the process since the login gets handled by their library/backend.

**Comment by bradmartin** [comment]
k so https://support.kinvey.com/support/discussions/topics/12000011802 their design was to make username case sensitive. So we'll just lowercase during sign up and login on the email field 👍
