### ISSUE TITLE
Generate activity data from OGPT Data

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#183]
We need to generate entries for `PushTrackerActivity` collection based on the `DailyInfo` packets received from the OGPT.

**Comment by p-ranav** [comment]
Is this an update to the pre-commit hook?

**Comment by finger563** [comment]
No - this is an event handler for the `pushtracker.daily_info_event` to convert the received daily info into activity data for the db and then push it to the db

**Comment by finger563** [comment]
same for the `pushtracker.distance_event`

**Comment by finger563** [comment]
since the user doesn't have an E2, they wont' be getting `SmartDriveDailyInfo` or `PushTrackerDailyActivity` into the db for the app to pull - the app will have to generate them and push them into the db based on those two packets received from the OGPT
