### ISSUE TITLE
Update onPreSave pre-commit hooks for SmartDriveUsage and PushTrackerActivity to use fixed-size lists for days

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#200]
Avoid sorting or removing duplicates by maintaining fixed-size lists.

**Comment by finger563** [comment]
Kamino cloned this issue to [appliedinnovation/PushTrackerKinvey](https://github.com/appliedinnovation/PushTrackerKinvey/issues/3)
