### ISSUE TITLE
Enhancement: move listpicker/slider dialogs into modal (or bottomsheet)

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#236]

**Comment by finger563** [comment]
@bradmartin are you still working on this or should @p-ranav move over to it?

**Comment by bradmartin** [comment]
I've got some code for it locally, it's not done yet. I'll move to finish it today/tomorrow tho 👍

**Comment by p-ranav** [comment]
@finger563 @bradmartin FYI related to this issue, chair_type and chair_make are now stored as enum in the DB (https://github.com/Max-Mobility/permobil-client/issues/286) - This is to make these entries language agnostic and better integrated with the translation service.

**Comment by bradmartin** [comment]
will finish up the slider-bottom-sheet component and replace the items on `settings.component` and wrap this up
