### ISSUE TITLE
Activity Component UI Layout

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#24]
![my-activity](https://user-images.githubusercontent.com/6006148/60134160-7fe8d580-9764-11e9-823b-664c4f3cdd75.png)

**Comment by p-ranav** [comment]
Since we don't have distance tracking, I'm currently showing `coast_time_avg` and `push_count` underneath `July 17 - 23`.

**Comment by p-ranav** [comment]
Do we have UI layouts for the Day and Month views for this tab?

**Comment by bradmartin** [comment]
I don't think so, but I believe we are just shooting for similar data display that Google Fit does. So they'll be charts. 

For simplicity, it might be best if we just do what you've done for the `Week` and use that for `Daily` but spread the bars out over the 24 hr period or do `start/finish` according to the usage data for each hour in between.

Monthly, just more bars so they'll need to be closer together.

Or we move away from the bar on monthly and figure out another good UI to display the monthly data. Thoughts?

**Comment by p-ranav** [comment]
Here's what I have for Daily activity. As you can see, it's very similar to Google Fit. You can track the progress of this tab here: #149 

My plans are the following:
1. Finish the pre-commit hooks in Kinvey to create Summary documents for PushTracker activity
2. Then, pull down this data in the Week view of the activity tab and style it similar to below. 
3. The Month view is currently a `RadCalendar` and connects with daily activity, i.e., when you click on a day there, it should take you to that day in the DAY view. Again, similar to Google Fit. 

![63118627-dce25a00-bf63-11e9-816c-12d3ffee05b3](https://user-images.githubusercontent.com/8450091/63126722-25a30e80-bf76-11e9-9dc0-a39a91e4b9f7.png)

**Comment by bradmartin** [comment]
😄 in that case I have no comment 👍  looks good to me. I'm sure we'll nee to adjust some styles or clean things up visually but looks good to me.

**Comment by bradmartin** [comment]
I didn't even realize that was our app in that screenshot, so yea looks really good to me.

**Comment by finger563** [comment]
Yes it looks great! 👍 @bradmartin do you know any libraries or have any ideas for replicating google fits month view?
