### ISSUE TITLE
Failed to write Characteristic

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#243]
We get this sometimes when trying to send a tap or settings - need to determine cause; it did not seem to happen in earlier builds.

**Comment by finger563** [comment]
perhaps related to [this comment](https://github.com/xabre/xamarin-bluetooth-le/issues/180#issuecomment-290560780) about async / await and bluetooth issues? we did re-write the code-base to move from promises to async / await

**Comment by finger563** [comment]
according to [the source code](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/bluetooth/BluetoothGatt.java) the `mDeviceBusy` variable locks some of these - so we need to prevent simultaneous operations as per the comments on [this page](https://devzone.nordicsemi.com/f/nordic-q-a/20175/how-do-i-resolve-a-characteristic-write-failure-on-android-nrf51)

**Comment by finger563** [comment]
It's a major undertaking - but perhaps we want to look into pulling out our bluetooth code for sd.w and only use what is necessary for SD - implemented in java? thoughs @bradmartin ? This would either be something that delays the launch or is done post-launch

**Comment by bradmartin** [comment]
Yeah I've expected for awhile we might be better off moving the Bluetooth into a native module. However, the benefits might be minimal unless any of the core Bluetooth on Android already runs off the main thread. If it's not that way by default then we get nothing really beneficial unless we write the native module using tasks, runnables, other threading models.

I think we should be okay waiting until post launch, we can likely improve the current implementation enough for the initial release. I'll review the links you posted about the Katie to catch up here.

**Comment by bradmartin** [comment]
So just chiming in on the one link about async not being on main. At least I think that's how it's done in C#. Been years since working specifically with it.

Everything JS and Android/Java for that fact is single threaded by default. So I don't think that helps much but you might already got past that comment and realized it.

**Comment by finger563** [comment]
@bradmartin i did find some stuff in the bluetooth library that could be fixed / improved (and i improved it) as well as allowing us to improve the connection management with the SD.  Initial testing seems to have improved / removed the behavior we were seeing - i'll continue testing and hopefully we don't see the characteristic write issues anymore (and our connection is more reliable)

**Comment by finger563** [comment]
For reference - the bluetooth library did not properly resolve (it resolved too early) when writing descriptors (as we do when we connect and get the services / descriptors for setting notifications) - so our code was using timeouts to hope that they had been configured properly. these timeouts did not work reliably, so the library has been updated to properly resolve now. this greatly simplifies the code needed when connecting to the device.

**Comment by finger563** [comment]
At this point we have removed one of the sources of the issue by changing how taps are sent - they will now not try to send while another tap is sending, but will instead be queued to be sent immediately after the current tap is done sending.  this appears to have resolved the issue, just need to fully test to ensure that taps do not wait too long to send / there is not too much latency between tapping and motor state change. Inital testing today seems promising.

**Comment by finger563** [comment]
Closing this issue for now
