### ISSUE TITLE
Update internal test builds for PT.M

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#251]
Assigning this to you @bradmartin since you've got the iOS build and testflight set up :)
There's no hard deadline, but we'd like to have a build out this afternoon or sometime this weekend

**Comment by bradmartin** [comment]
Will go ahead and pull master and push it 👍 - I'm still working on fixing some of the perf issues,  I've identified a few areas in our code that are causing problems but then also trying to improve the overall approach with how we use the tabview to prevent unnecessary loading/rendering/data fetching when tabs aren't shown, which is possibly a bug in NS core modules that I'm gonna report, just need to repro it in an example to be certain it's not OUR logic doing something silly.

**Comment by finger563** [comment]
Closing because I believe these builds rolled out
