### ISSUE TITLE
Update WearOsMessaging Lib to support various message events

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#253]
Need to handle the https://github.com/Max-Mobility/WearOsMessaging/blob/1e020ba80eca70a449059eff76465c6b47790b4d/wearosmessenger/src/main/java/com/github/maxmobility/wearmessage/DataLayerListenerService.java#L75 event here for various use cases.

I think starting out:

```
KINVEY_TOKEN,
START_PUSHTRACKER_MOBILE,
START_PUSHTRACKER_WEAR,
START_SMARTDRIVE_WEAR
``` 

will be the initial 3 use cases for messages that we wanna handle.

##### Android
- [x] Determine if there is an available connection: use the wear os nodes / capabilities api to find nodes (paired / connected wear os / phone devices) which expose a capability we define
- [x] Send Data: mostly done AFAIK
- [x] Send Message: mostly done AFAIK
##### iOS
- [x] Determine if there is an available connection: scan for bluetooth devices with a specific bluetooth service which is advertised by the pushtracker wearos app - and return them
- [x] Send Data:
  * determine what available connections exist and prompt the user to select which one they want to send to (use the reported device name)
  * send the data to the specific characteristic of the service we specified
- [x] Send Message:
  * almost the same as above, but using a different characteristic

**Comment by finger563** [comment]
@gcastro103  can you update the WOM lib to add support for the nodes / capabilities API for the final item in the issue?

**Comment by finger563** [comment]
closed - node / capability api was added to WOC instead of WOM for now.
