### ISSUE TITLE
Birthday should not be a required field in the Signup tab

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#271]
Last we discussed, age was not a required profile setting. Has this changed?

**Comment by bradmartin** [comment]
Don't think so, I assumed it was required for data analysis. Is there any privacy issue requiring it? Most apps I think require it at least, but of course, William knows end users and the data analysis needs better than I 👍

**Comment by finger563** [comment]
We definitely don't want to require age in sign-up :) Go ahead and remove it and I'll verify with legal.
