### ISSUE TITLE
Go through app and ensure all text goes through the translation service

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#280]
for all text visible to user - on pages, in dialogs, etc.

**Comment by p-ranav** [comment]
### Questions:
* Are we translating units?
  - Should we translate the `s` in `5.5 s` for coast time?
  - What about distance units? `mi` vs `km` - Should we translate these too? 
  - What about `miles` or `kilometers` in the home tab?

**Comment by p-ranav** [comment]
@finger563 

Assumption after #315: The language keys in Kinvey ***must match exactly*** with the `APP_LANGUAGES` enum:

```typescript
// enums/app-language.ts
export enum APP_LANGUAGES {
  'English' = 'en',
  'Spanish' = 'es',
  'German' = 'de',
  'French' = 'fr',
  'Japanese' = 'ja',
  'Korean' = 'ko',
  'Dutch' = 'nl',
  'Russian' = 'ru',
  'Swedish' = 'sv',
  'Chinese (traditional)' = 'zh-CN'
}
```

```json
// Kinvey Files
// Firmware change_notes
{
  "en": [],
  "es": [],
  "de": [],
  "fr": [],
  "nl": [],
  "ja": [],
  "ko": [],
  "zh": []
}
```

As you can see, these two objects are not consistent. In Kinvey, Russian and Swedish are missing from the change_notes object. In Kinvey, simplified Chinese is represented with the key `zh` while the same key in APP_LANGUAGES is `zh-CN`. 

These keys need to be consistent (exact match, actually) or else the change notes will not correctly show in the app in the `UpdatesInfoComponent` based on the user's language preference.
