### ISSUE TITLE
Update chair info storage

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#297]
Right now chair make & type are stored as integers which are derived as indexes into a list of strings - but in the case of chair make we want this list of strings to not only be translated but also in alphabetical order, which means that as the list gets updated (which it may as the market changes) old indexes are now invalid.  We should move to an enum which maps to strings that we can then use with the translation service.

**Comment by p-ranav** [comment]
@finger563 Can you review these commits and see if these updates make sense? If yes, you can close this issue.

**Comment by p-ranav** [comment]
@p-ranav When saving to Kinvey, save the English version and not the translated version
