### ISSUE TITLE
Enhancement: clean up UI layouts in SD.W

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#316]
- Need to flatten the layouts as much as possible in order to reduce the measure/draw pass on the layouts.

- Look into using `modals` when showing the offscreen swipedismisslayouts on wear apps. This might not work because the modals are dialogfragments on android, but it's an idea we can test to see if possible. This would break up several portions of the UI into smaller components and move logic out of the main-pages view-model file.

**Comment by p-ranav** [comment]
New Pages that are shown as modals in the main view:
- [ ] About
- [ ] Error history
- [ ] Settings
- [ ] Change Settings
- [ ] Scanning
- [ ] Wireless Updates

**Comment by p-ranav** [comment]
We're showing a `Close` button in wireless updates (in different scenarios) so you can close the modal.

**Comment by p-ranav** [comment]
Back button not working on some modals. Investigating.

**Comment by finger563** [comment]
as far as i can tell this issue is closed? or @bradmartin should we continue to go through and flatten the layouts like in PT.W?

**Comment by bradmartin** [comment]
- [ ] Could remove the `Ripple` layout on the menu items on the main-page.xml
- [ ] Could flatten `settings-page.xml` to use a Grid and not the nested Grids for the 'list items' (PT.W has example so should be copy/paste/change)

That's all I see at quick glance on SD.W

**Comment by p-ranav** [comment]
Flattened `settings-page.xml` layout as suggested aa8250d0ada274ac39cae6075599e0601809ad1a

**Comment by finger563** [comment]
- [ ] update battery / distance charts to not use repeaters / arrays, but instead bind directly to specific variables / indices into the array

**Comment by finger563** [comment]
I think we've updated the layouts as much as we can - time to look into lifecycle handling and other start up performance as per #276
