### ISSUE TITLE
ios load style issues

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#333]
when loading the app (regardless of active component) the style is not applied for a couple of seconds and the app is absolutely hideous.

**Comment by finger563** [comment]
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-09-24 at 09 35 27](https://user-images.githubusercontent.com/213467/65521478-ed64e900-deae-11e9-88d8-393dee990ab9.png)

**Comment by bradmartin** [comment]
This is related to the `themes` plugin method `applyTheme` executing. Looking into solutions to prevent the `3s` operation that seems to prevent styles from applying to rendered views.

**Comment by finger563** [comment]
I think we can close this for now after 68b42ac - the remaining work is related to #383 which is a separate issue.
