### ISSUE TITLE
ios bottomsheeet style

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#345]
on ios the bottomsheets that pop up have a lot of margin between the cancel / ok buttons and the bottom of the device that is filled in with white

**Comment by bradmartin** [comment]
the empty white space at the top and bottom of the bottom sheet is being applied by the bottomsheet plugin source for iOS. Seems that too high a value is being supplied to the `CGSizeMake` being set on the sheet content size.

Working on the current local fork for now, will suggest PR fix to repo on improving this.

The layouts on the sheets in regard to the button spacing I have fixed locally, just not pushed, just adding a new column in the parent grid to put the buttons next to the `*` column.
