### ISSUE TITLE
Changing acceleration or tap sensitivity in profile settings page shows NaN%

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#352]
Related to #350. A closeCallback needs to be passed to `SliderSheetComponent`

![Screenshot_20190925_090025_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/65607962-0df67700-df73-11e9-91fd-7cd2b3908f67.jpg)

**Comment by bradmartin** [comment]
Reference: wasn't passing the correct callback portion of the `result` in the `subscribe` of the bottomsheet for updating the setting value.
