### ISSUE TITLE
update smartdrive scanning to return quickly if there is a smartdrive

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#359]
should reduce the time required - though it may make it harder to ascertain if there are multiple smartdrives around.

at the very least we should have a way to quickly return from scanning if we want.

**Comment by finger563** [comment]
aabecea0a55a1b2e8103d8afe0623bcc55d5718e was related

**Comment by p-ranav** [comment]
This can be closed now yeah?

**Comment by finger563** [comment]
Yea it's good - talked to Ben and we determined that we like this behavior in the mobile app, but will keep the current scanning functionality in the SD app.
