### ISSUE TITLE
Update splash image for ios

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#368]
right now it shows the permobil logo on a black background.

**Comment by finger563** [comment]
was this fixed? i still see the old permobil logo on the latest build on `master`

**Comment by bradmartin** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2019-10-07 at 15 29 54](https://user-images.githubusercontent.com/6006148/66346241-56b91300-e917-11e9-8bb0-454a298b3470.png)
