### ISSUE TITLE
Regenerate PT.W splash screen

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#381]
right now the SD.W splash screen is small and easily fits on the screen while looking nice - however the PT.W splash screen does not even fit onto the E2's screen (it's clipped a little bit). The PT.W splash screen should be regenerated using the same format as the SD.W splash screen.

This is related to #91 and may be the last required feature for PT.W inset handling.

**Comment by bradmartin** [comment]
I don't think I used marketing's icon, but I just ran the other thru the asset generator in android studio and increased the padding on the SD.W splash. 

I'll do this for PT.W, think it was only 10% padding applied.
