### ISSUE TITLE
Investigate turning motor off for high-impact events

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#406]
update TapDetector to inform the main process that there was a high impact event (e.g. `mustTap = true`) for which we may send a `stopMotor` command.

**Comment by guo-max** [comment]
Found out tappings on a soft surface have higher max_jerk than tapping on a hard surface. The max acc collected from the data_collector App is about 45 m/s2 and the max acc from the SmartDrive App is about 95 m/s2.
