### ISSUE TITLE
Show no data cause on journey tab

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#420]
When there's no data, the journey tab is empty, and doesn't say that there's no data yet or if it's due to no network connectivity or any errors. We should have messages for those cases

**Comment by p-ranav** [comment]
![Screenshot_20191008_082326_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/66399289-f8d30c80-e9a4-11e9-99d1-a1ee01363e00.jpg)

![Screenshot_20191008_082337_com permobil pushtracker](https://user-images.githubusercontent.com/8450091/66399294-fc669380-e9a4-11e9-9700-c2e058f86c89.jpg)
