### ISSUE TITLE
name and email should both have width set and become multiline

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#429]
otherwise the privacy button shows off screen
![Screen Shot 2019-10-09 at 8 28 23 AM](https://user-images.githubusercontent.com/213467/66485632-c42b8780-ea6e-11e9-8c61-90d0e3332eaf.png)

**Comment by bradmartin** [comment]
Should be simple fix, adjust the layout and get rid of the stack and use grid rows/cols and should handle the wrapping without messing the privacy button 👍
