### ISSUE TITLE
Enhancement: Migrate app scss to use the new NS theme core

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#448]
https://github.com/NativeScript/theme

Since iOS 13+ and Android 10 now provide a system wide user setting for `Dark Mode` preferences. We would be able to drop the `themes` plugin that we currently use and the approach we have (since we started this before android/ios announced their plans). Using the new theme-core from NS should allow us simpler/better usage for supporting dark mode on iOS/Android. 

Not sure on the time estimate, I haven't looked too far into the changes required, only seen the discussion some.

**Comment by finger563** [comment]
@bradmartin how is this related to the pt.w and sd.w apps? would this help with ambient mode or what?

**Comment by bradmartin** [comment]
No benefit on ambient mode. There is prob no major benefit, so we can prob just not worry about this. The themes are just css/scss "helpers" to make styling easier and what we have is fine implementation wise. No net negatives really.

**Comment by finger563** [comment]
sounds good, then i'll close this issue for now.
