### ISSUE TITLE
Home tab shows white for up to 10 seconds when opening app

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#462]
not sure what the cause - even the tabs at the bottom of the page don't load / show so it could be other code loading / layout happening that we're not seeing. need to profile and see what the root cause is. for reference this is testing when in the pushtracker e2 configuration and on android.

**Comment by bradmartin** [comment]
Might try using `visibility` on the root bottomnavs, and not `ngIf` see if that helps any with different config. Also, be sure the value that's in the `ngIf` (contorl config) is available as soon as possible so it can load the UI we need/want.

**Comment by finger563** [comment]
yea i'm wondering if it's related to the `ngIf` since iOS doesn't seem to have this issue

**Comment by finger563** [comment]
so i see the log:
```
JS: Sentry Breadcrumb:  {
JS:   "message": "[HomeTabComponent] Loaded",
JS:   "category": "Info",
JS:   "level": "info"
JS: }
```
even though I don't see anything on the screen - not even the tab navigation buttons at the bottom - for almost the whole 10 seconds

**Comment by bradmartin** [comment]
is this on your pixel phone? I haven't seen it myself, but maybe it's a specific configuration/run process...

**Comment by finger563** [comment]
It seems to be somewhat linked to my user account as best we've been able to tell

**Comment by p-ranav** [comment]
It's more than just your account because your account loads OK on other phones..
