### ISSUE TITLE
improve performance of pager in wear apps

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#489]
- [ ] startup performance - moving to pager from basic scrollview dramatically altered the startup time for the PT.W app - indicating that it is a major factor in our startup performance for SD.W as well.
- [ ] runtime performance - similarly we notice a difference in the run-time performance of PT.W after moving to pager; fixing this may help both SD.W and PT.W respond better

**Comment by bradmartin** [comment]
https://github.com/Max-Mobility/permobil-client/commit/1e466ed52d24a74f4c7c5e471fb9bedf91859228

**Comment by finger563** [comment]
Right now we're looking into dynamically loading the pages using the builder api - so i'm removing this off the v2.0.00 release timeline.

**Comment by finger563** [comment]
closed by #719
