### ISSUE TITLE
Set release version numbers

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#504]
- [x] pt.m (iOS / Android): `2.0.00`
- [x] pt.w: `1.0.00`
- [x] sd.w: `1.0.00`

**Comment by finger563** [comment]
@bradmartin we're moving to the version strings listed above in this issue - what do you recommend for updating the actual version codes in the files?

**Comment by bradmartin** [comment]
just bump version codes as they are, nothing fancy or we'll have issues
