### ISSUE TITLE
Update app store graphics / text

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#507]
### Apple App Store
- [x] text for PT.M
- [x] graphics for PT.M

### Play Store
- [x] text for PT.M / PT.W
- [x] graphics for PT.M / PT.W
- [x] text for SD.W
- [x] graphics for SD.W

**Comment by finger563** [comment]
Apple app store:
[Uploading Jpegs.zip…]()

**Comment by finger563** [comment]
Google play store (pushtracker):
[Google Play.zip](https://github.com/Max-Mobility/permobil-client/files/3842533/Google.Play.zip)

**Comment by finger563** [comment]
@bradmartin  I've updated the text / graphics in the play store for SD.W and PT.M / PT.W

**Comment by bradmartin** [comment]
I copied the description from google to apple.

So the iOS graphics are a bit odd. Only have 2 screenshots in the zip file... need more of the actual app, not promo type graphics that aren't the app.

**Comment by bradmartin** [comment]
I'll upload them... but they might say something about the graphics

**Comment by finger563** [comment]
well we have screenshots we can take if we need (or have taken?)
