### ISSUE TITLE
investigate moving back to kinvey sdk for all kinvey related data 

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#520]
so that we can let them handle the caching of data / pushing to the backend. should help clean up the code some as well. will need to evaluate effect on performance (if any) which I remember might have been the original reason for moving away from them - though I'm not sure if we determined it was actually the fault of the sdk; it might have been issues with the hooks or other code

**Comment by bradmartin** [comment]
Trying to recall exact reason but I think we're okay to move back to the SDK now and use the actual `datastores` kinvey provides without any perf hit. So this should be fine to do now with everything in place as it is now for perf.

**Comment by finger563** [comment]
Need to ensure that if we set up the usage as datastores, that they don't try to sync the *whole* database onto the phone - they only sync what we ask them to (e.g. that user's data)
