### ISSUE TITLE
Feature: Watch Layout changes and font

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#592]
- [x] complication is not centered in the vertical space between the smartdrive button and the battery
- [x]	font for time at the bottom is a little small and does not match the font / styling that is used for time in the SmartDrive MX2+ app
- [ ] Opening the MX2+ app takes a little while - longer than it does if you set it as an app shortcut

**Comment by bradmartin** [comment]
![Screenshot at Dec 03 15-06-34](https://user-images.githubusercontent.com/6006148/70089799-89614e00-15de-11ea-9d60-f3a8aba32a04.png)

SD.W on left - SD Watchface on right.

Looks like the Watchface time font size is larger. It's being set to 24sp I believe, we can change to `dp` and use `18` which is the font-size being used in SD.W.

Complication looks okay, but does need to be changed on the `config activity` with the new sd.button no-dpi scale change from yesterday.

Looking into why the app shortcut is faster than our button tap to open the SD.W app from the watchface interaction, likely some code is running slower in the service checking the bounds of the tap.

**Comment by finger563** [comment]
actually the opposite is true for the time font size - on the actual E2 - the font size used by our time is smaller than the font in the app @bradmartin

**Comment by finger563** [comment]
![](https://i.imgur.com/M25FDqv.jpg)
![](https://i.imgur.com/YqDfGQ7.jpg)

**Comment by bradmartin** [comment]
Gotcha, running on the E2 now to compare.

We use `18` font size [here](https://github.com/Max-Mobility/permobil-client/blob/master/apps/wear/smartdrive/app/scss/_power-assist-default.scss#L101) and NS uses DPI which should be standard `dp` on Android textSize. I've changed the Watchface to use `18` now but it's using `sp` to accomodate for user font size on the device. If we don't care about that we can use `dp` which might align better.

https://developer.android.com/guide/topics/resources/more-resources.html#Dimension](http://developer.android.com/guide/topics/resources/more-resources.html#Dimension)

**Comment by bradmartin** [comment]
Just opened a PR to get the fonts more aligned. Also, slight adjustment on the complication position, might need a little more changes bc the complication is positioned using the `Rect()` in the code, vs the layout being defined in the layout.xml.

**Comment by finger563** [comment]
That makes sense - also think that part of it is that we're showing the `:` as a separate string which adds to the spacing and makes the time look more different than it actually does

**Comment by bradmartin** [comment]
Yea, not sure of a cleaner way to do that since to make it look more like other watch faces they "blink" the colon in the time string. That was some code from the Google code lab for watch faces I think Xing added in. 

![image](https://user-images.githubusercontent.com/6006148/70098113-c0405f80-15f0-11ea-8ae0-14f7d29495ee.png)

**Comment by bradmartin** [comment]
That's running what I have in the PR I just opened... so if you merge that or run that branch your should look similar now. The font style is just `sans-serif` which should be OS default and we don't set the font-family in the SD.W app so I just left it sans-serif which is what android studio defaulted the `TextView` to. I think they look the same now. I also lowered the size to `18sp` so I think it looks pretty close to the SD.W app now. Let me know if you see something different though.

**Comment by bradmartin** [comment]
I could play with the `textAlignment` on the `TextViews` in the watchface time string, right now I'm using `viewEnd` on the hour, `center` on the colon, `viewStart` on the minute portion so get them in the center of the watch face like they are. There is also `textEnd` and `textStart`, in the UI designer it's hard to see what it actually changes (might be nothing in this instance) so will have to run it to see.

**Comment by bradmartin** [comment]
@finger563 - if you can run the PR branch opened for this feature and see what Ben thinks. My last image ^^ is on my E2 and the font looks better and the complication seems to be better positioned between the circles and the button.

I've looked at the SD app opening performance, the actual code is executed in just `ms` and the activity is just slow to actually open. Not sure what's causing it at the moment because our code completes so quick it's like the system is just hanging to open the app with the Intent to start the Activity. I'll see if I can find an alternative that might provide better perf++
