### ISSUE TITLE
E2 Tap Detector doesn't work after fix for #649

### ISSUE THREAD

**Issue by p-ranav** [Max-Mobility/permobil-client#652]
Original issue: #649 
Merged bug fix: #651 

Fixes remaining:
- [x] data mutation from `const total = this._previousData.reduce(...)`
- [x] data mutation from `const max = this._previousData.reduce(...)`
- [x] data mutation from `const min = this._previousData.reduce(...)`
- [x] jerk thresholds for tap detector when system is up to date
- [x] system version jerk threshold factor for tap detector when system is out of date
- [x] tap lockout time (perhaps increase it from 100 ms)

**Comment by finger563** [comment]
Going to move the remaining items on this issue into another issue for updated tuning so that the actual fixes can get pushed onto master and this branch can be merged.

**Comment by finger563** [comment]
this was closed by #700
