### ISSUE TITLE
Chore: Test if invalidate during ambient displays correct time for watchface

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#699]
An idea to try and get rid of the time hacks we have currently, we'll need to analyze battery life after this change to ensure it's not killing the watch since `invalidate()` on the entire layout can be expensive.

Can try [here](https://github.com/Max-Mobility/permobil-client/blob/master/apps/wear/smartdrive/app/App_Resources/Android/src/main/java/com/permobil/smartdrive/wearos/watchface/digital/DigitalWatchFaceService.java#L689) or in the `onDraw()` adding an `ambient` check and then `invalidate` after the `drawTimeStrings()` method.

**Comment by finger563** [comment]
@bradmartin according to the docs for [WatchFaceService.Engine::onTimeTick](https://developer.android.com/reference/android/support/wearable/watchface/WatchFaceService.Engine.html#ontimetick) we should be able to rely on that for date / time / timezone changes and not use the receiver - which may help with the context being correct and ensure that everything gets updated properly - if we recalculate the strings and call invalidate here then we should be good I think?

**Comment by finger563** [comment]
figured it out - `drawTimeStrings()` needs to be called between `mRelativeLayout.measure(...)` and `mRelativeLayout.draw(...)` - otherwise we're always drawing the **previous** value of the time strings
