### ISSUE TITLE
Chore: review modal and view.android.js for perf++

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#758]
In addition to #749 we can look into further optimizations into the JS side of things to see if we can pinpoint specific slowdowns and increase our WearOS app perf++ even more.

**Comment by bradmartin** [comment]
Some things to look at/consider:

Do we ever use `animated: true` in the modals, I don't believe so bc they were "snappier" to display initially without having an animation. However, we could look to see if an animation makes it feel better in terms of UX and if it doesn't slow things down now then we leave the `animated` in the modal source code. If we don't and it's not good UX/perf to have it, then we just remove it from the modal creation for less ops during that function.

**Comment by finger563** [comment]
Yea that seems reasonable - right now we're definitely not using animated anywhere in the modal creation primarily for performance reasons, so we can definitely remove it if it makes it faster

**Comment by bradmartin** [comment]
Yea, I'm kinda curious if using a different modal approach would perform better entirely. At one point there was a `dialog` plugin that allowed you to put a `View` inside of it and render it. I'd have to look again at what it allowed and how it worked but less is best on the watches for sure.

For now tho, I'm gonna keep modifying different pieces of the modal code and logging the nanotime to see what takes the longest and if we don't need/use it, we'll just comment it out for now in our forked-plugins dir (since the comments should be removed on release builds they won't matter and it'll help us with the upgrade path of the custom changes we need in the core).
