### ISSUE TITLE
Develop watchface for bundling with smartdrive app

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#76]

**Comment by finger563** [comment]
Will likely have the same design as the main page of the smartdrive app - e.g. two outer rings for battery display, a big *blue* button in the middle which opens the smartdrive app, and then time / date below.  similarly to the smartdrive app, when the watchface is in ambient mode it will hide the button and the time and date will take center position.  above the button (where the estimated range currently displays) the watchface can have a complication position.

**Comment by finger563** [comment]
https://codelabs.developers.google.com/codelabs/complications/index.html?index=..%2F..index#0

**Comment by finger563** [comment]
https://github.com/googlesamples/android-WatchFace

**Comment by finger563** [comment]
https://github.com/android/wear-os/tree/master/WatchFace has replaced the previous sample

**Comment by finger563** [comment]
@ken-max  can you post the design image you made for ben / the shroud here?

**Comment by ken-max** [comment]
![Watch Face3](https://user-images.githubusercontent.com/30480540/64890218-b3851e80-d634-11e9-9aed-c6e7cb57a603.png)

**Comment by finger563** [comment]
The blank area above the MX2+ button provides space for supporting a single complication that the user can select (as with any other watch face)

**Comment by finger563** [comment]
The button in the middle either opens the smartdrive app (if installed) or opens the play store to the app (if not installed)

**Comment by finger563** [comment]
See [these android docs](https://developer.android.com/training/wearables/watch-faces/service) on how to make a watch face service for bundling the smartdrive watch face within the smartdrive app

**Comment by finger563** [comment]
Ambient mode for the watchface should be identical to ambient mode for the app - the time / date display becomes big and in the middle, with the center button hidden

**Comment by finger563** [comment]
https://proandroiddev.com/build-watch-faces-for-wear-os-44be9d536a9a

**Comment by finger563** [comment]
make android studio project for `SmartDrive MX2+` watchface within `apps/wear/watchfaces`

**Comment by finger563** [comment]
@xing-w  we use these dependencies for our animated circle code in our smartdrive / pushtracker apps:
https://github.com/Max-Mobility/permobil-client/blob/master/forked-plugins/nativescript-animated-circle/platforms/android/include.gradle

which just goes to our fork of circle progress view:
https://github.com/Max-Mobility/Circle-Progress-View

**Comment by bradmartin** [comment]
Closing since bulk of work has been done and only bug/features remain for initial test release.
