### ISSUE TITLE
Enhancement: remove date-fns dependency from Wear Apps

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#779]
To reduce overall bundle and dependency list, we can remove `date-fns` and use plain JS or Java we have already written in the watchface for formatting and date manipulation work.

**Comment by finger563** [comment]
The functions we use are:
```
closestIndexTo
eachDay
format
isSameDay
isToday
subDays
```

`format` can probably be replaced by `SimpleDateFormat` which means we can stop importing all the languages and can just use `SimpleDateFormat::format(...)` which automatically uses the device language (as we want to).

**Comment by bradmartin** [comment]
Was reading into this specifically with regard to what popular Java libs there are and Joda seemed to be #1. Using a java lib doesn't impact our boot up since it's not JS being parsed on startup. So looked at that, but Joda website says if you're on Java8 to use the built in stuff now.

**Comment by finger563** [comment]
@bradmartin i've updated SD.W to not use the `format` function so we don't use their `locale`s - this should reduce import size. Since we're only using a few other functions, we should be good from a size / import / processing perspective, right?

**Comment by bradmartin** [comment]
Yes. Now we need to update the dependency version in the package.json and that will def. be a good thing to get knocked out
