### ISSUE TITLE
Synchronizing re-runs every time screen comes back on

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#794]
in ambient mode, going into & out of ambient doesnt trigger re-sync with server (while on settings page), but when screen always-on is disabled on the watch (meaning the screen turns off) then turning the screen off and then back on triggers re-synchronizing with the server - this is annoying at best.

**Comment by bradmartin** [comment]
When we have #805 merged to fix the activity events, this should be fairly simple to fix.

We'll add the event listener for the `activityResumed` event and  if it's been resumed we will skip the `downloadTranslations` call.

Need to think about that a bit, to ensure proper handling but that's quick thoughts on fixing it now that we know why those events weren't firing 💯
