### ISSUE TITLE
Enhancement: target ES2017 for WearOS apps

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#814]
Our WearOS apps can target ES2017 since they're android only and NS 6.4.1 uses the version 8 of V8 for runtime which has direct support for ES2017 features that we use (async/await, etc.)

This should lead to smaller bundles and a small performance boost since the JS will be directly supported by the engine.

**Comment by bradmartin** [comment]
Sadly, right now after some discussion with NS runtime team. The runtimes don't fully support ES2017+ in regard to the SBG (Static Binding Generator), they have discussed updating it, but suggested we try extending the native classed in pure JS to not use the transpiled ES2017 functionality with `extend`. I tried this but the app was still crashing. We'll keep this open but on hold for a later date with low priority right now.

**Comment by finger563** [comment]
Does this work now with #820 across platforms (since ios is now also using V8?)

**Comment by bradmartin** [comment]
So it wasn't a V8 thing. It's due to the fact we used the native class decorators inside our app code and there was nothing to transform the code in those files to correctly target ES2017.

However, it looks like NS is about to push a mono repo of majority of the project to ease development and in that I believe there is a new approach for modern tree-shaking of the JS code and this will have a transformer to allow us to extend native classes in JS and the native files be generated correctly. So this should be possible in the next release if I was following along correctly. So fingers crossed.

**Comment by bradmartin** [comment]
https://github.com/NativeScript/NativeScript/commit/f39d2f00523baf447023dd30bb2aeee05b24a396

**Comment by finger563** [comment]
@bradmartin now that we're on {N} 7.X is this something we can do?

**Comment by bradmartin** [comment]
it's already done now :) forgot this was opened 💯
