### ISSUE TITLE
Bug (PT.M): changing calendar date not working

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-client#850]
Per William: clicking on the calendar doesn't change the tab on the page (e.g. to week / day) unless it's behind the currently selected date (regardless of what that date is) - but it does actually change the date

**Comment by bradmartin** [comment]
Closing, the calendar seems to respond correctly if you select the current date or any date prior. This might have always been the functionality as future dates wouldn't have any data anyway so I think we're good.

**Comment by finger563** [comment]
Yea the issue I had (admittedly, in a debug build, not in release) was that once I selected a prior date to today, I was unable to select a date between the newly selected date and today. If that's working now, then I think it was probably just a build issue on my side.

**Comment by bradmartin** [comment]
Yea seems fine, can go back and select dates then go forward. Anything works except future dates.
