### ISSUE TITLE
Handle inset (for devices with chins)

### ISSUE THREAD

**Issue by finger563** [Max-Mobility/permobil-client#91]

**Comment by finger563** [comment]
![20190509_160752_PDT](https://user-images.githubusercontent.com/213467/64429285-3d544b00-d07b-11e9-9464-91075bf6dc5a.png)

**Comment by finger563** [comment]
![20191209_162917_PDT](https://user-images.githubusercontent.com/213467/64864073-e232d300-d5fb-11e9-9c98-66fe7927a740.png)

**Comment by finger563** [comment]
@bradmartin  do you know why our splash is so large / cut off? Our source image (and the generated images in the drawables folders) are all well inset within the square

**Comment by finger563** [comment]
I think the problem is that the watch is registering as a high-dpi device even though it's a small screen - so it's selecting a high dpi image (which has far more pixels than the screen does)

**Comment by bradmartin** [comment]
The device shouldn't be doing that. Are you certain the images in the drawables are scaled correctly? Did you generate them with a tool? Maybe misplaced the wrong size in the wrong drawable?

**Comment by finger563** [comment]
As best I can tell (via emulator testing) the splash screens are good to go after the pushes @bradmartin  made a few hours ago (76ec26dc8a35cbb18a5e4301e23e8ea633778510 and fef49e5ef0b6d6f65dae0e050770c2c5e6643306).  Will wait until the next release to determine if google is happy with our handling of screen sizes

**Comment by finger563** [comment]
After the update to the splash screen, the MX2+ app was accepted in to the play store - so I believe we can close this issue :)
