### ISSUE TITLE
Feature Request: Port MX2 app to the Watchy Smartwatch

### ISSUE THREAD

**Issue by shsorbom** [Max-Mobility/permobil-client#911]
# Introduction:
The Watchy is a smartwatch with an e-papar display, built by hobbyists and available for $60 USD.

# Why smartdrive users would Benefit:
The current TicWatch implementation of the Smart Drive watch has a major limitation compared to the customized options Max-Mobility used to offer: battery life. The original watch could work for three days on a single charge. The MX2 Pushtracker could reliably work for 24 hours. The TicWatch implementation...barely lasts 5.

But Watchy could change that. Because Watchy uses an e-paper display, it can last up to 5 DAYS on a single charge. As a bonus, the display can be read in full daylight.

# Challenges:
Watchy is a hobbyists kit. It uses its own C SDK on an Arduino board. Users currently need to assemble it on their own. But if Max-Mobility one day could ship it, that issue wold be solved.

Here is a link: https://www.tindie.com/products/sqfmi/watchy/

**Comment by finger563** [comment]
Hi @shsorbom thanks for the suggestion!

We have been following the watchy kit with some enthusiasm - it's a very nice design and definitely fun to put together and customize. We are looking into ways of supporting (verifying / validating) more watches, though at this time I don't think we'll be able to support a system such as watchy as that would require a full re-write of our existing software(s).

That being said - I do agree with you; the watchy would be an excellent upgrade from the PushTracker and would provide a nice alternative to the PushTracker E2, so we'll continue looking into it / evaluating it and hopefully at some point in the future we'll be able to more officially support it - but of course I can't guarantee that it will happen. I hope that makes sense, and please feel free to reach back out if you have any further questions / comments.

Thanks again!

**Comment by finger563** [comment]
On a related note @shsorbom - I would suggest you reach out to our technical support / customer experience team as the 5 hours you quoted regarding the PushTracker E2 is less than what you should be getting, so hopefully they can help ascertain what the root cause is and help resolve / mitigate it :)
